### ISSUE TITLE
Set acceptableRemoteVersions to "*" in @Mod

### ISSUE THREAD

**Issue by TheRandomLabs** [duely/SuperflatCaves#1]
So vanilla clients can connect to servers with this mod installed.

**Comment by noobanidus** [comment]
Excellent point, I'll try to do a new release today.

**Comment by noobanidus** [comment]
Unfortunately the chaos of getting new alpha builds out of both Arcane Archives and the Roots family completely distracted me from this, meaning I forgot about it until just now. I'm working on it while I wait for the modpack to load -- I had made some other additional changes as well.

**Comment by noobanidus** [comment]
And done! I'm making a new release presently. I'm so sorry that it took me so long to get this working, I had a bunch of other changes in progress and I just couldn't get the time to test everything fully. As far as I'm aware it's working perfectly at the minute though.
